services:
  postgres:
    image: postgres:15
    container_name: pgs-postgres
    restart: always
    environment:
      POSTGRES_DB: pgs_db
      POSTGRES_USER: pgs_user
      POSTGRES_PASSWORD: pgs_pass
      TZ: Asia/Tehran
    ports:
      - "5432:5432"
    volumes:
      - pgs_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgs_user -d pgs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgs_postgres_data:
